# Site
repository: seokwoo-jung/modern-resume-theme
favicon: images/favicon.ico

# Personal info
name: Seokwoo Jung
title: AI research engineer
email: aerojung123@gmail.com
website: https://seokwoo-jung.github.io/

# Social links
github_username:  seokwoo-jung
linkedin_username: seokwoo-jung

# About Section
# about_title: About Me
about_profile_image: images/profile2.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a research engineer at LG Electronics CTO Division. I am currently working on a AI aided vehicle system at automotive & business solution center(A&B Center). My interests are perception algorithms and optimization on edge device for intelligent vehicle. 

  I am most skilled in: <mark>Deep Learning</mark> and <mark>Computer Vision</mark> for <mark>Autonomous driving</mark>.
  
  
  Programming Language & Framework : <mark>C/C++</mark> <mark>Python</mark> <mark>Tensorflow</mark> <mark>Pytorch</mark> <mark>Caffe</mark> <mark>Tensor RT</mark> <mark>SNPE</mark> etc.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: seokwoo-jung/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

darkmode: true
